/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmporiumIndexRouteImport } from './routes/Emporium/index'
import { Route as AboutIndexRouteImport } from './routes/About/index'
import { Route as EmporiumProductIdRouteImport } from './routes/Emporium/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmporiumIndexRoute = EmporiumIndexRouteImport.update({
  id: '/Emporium/',
  path: '/Emporium/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/About/',
  path: '/About/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmporiumProductIdRoute = EmporiumProductIdRouteImport.update({
  id: '/Emporium/$productId',
  path: '/Emporium/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Emporium/$productId': typeof EmporiumProductIdRoute
  '/About/': typeof AboutIndexRoute
  '/Emporium/': typeof EmporiumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Emporium/$productId': typeof EmporiumProductIdRoute
  '/About': typeof AboutIndexRoute
  '/Emporium': typeof EmporiumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Emporium/$productId': typeof EmporiumProductIdRoute
  '/About/': typeof AboutIndexRoute
  '/Emporium/': typeof EmporiumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Emporium/$productId' | '/About/' | '/Emporium/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Emporium/$productId' | '/About' | '/Emporium'
  id: '__root__' | '/' | '/Emporium/$productId' | '/About/' | '/Emporium/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmporiumProductIdRoute: typeof EmporiumProductIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  EmporiumIndexRoute: typeof EmporiumIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Emporium/': {
      id: '/Emporium/'
      path: '/Emporium'
      fullPath: '/Emporium/'
      preLoaderRoute: typeof EmporiumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About/': {
      id: '/About/'
      path: '/About'
      fullPath: '/About/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Emporium/$productId': {
      id: '/Emporium/$productId'
      path: '/Emporium/$productId'
      fullPath: '/Emporium/$productId'
      preLoaderRoute: typeof EmporiumProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmporiumProductIdRoute: EmporiumProductIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  EmporiumIndexRoute: EmporiumIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
