/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmporiumIndexRouteImport } from './routes/Emporium/index'
import { Route as AboutIndexRouteImport } from './routes/About/index'
import { Route as EmporiumProductIdIndexRouteImport } from './routes/Emporium/$productId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmporiumIndexRoute = EmporiumIndexRouteImport.update({
  id: '/Emporium/',
  path: '/Emporium/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/About/',
  path: '/About/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmporiumProductIdIndexRoute = EmporiumProductIdIndexRouteImport.update({
  id: '/Emporium/$productId/',
  path: '/Emporium/$productId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/About/': typeof AboutIndexRoute
  '/Emporium/': typeof EmporiumIndexRoute
  '/Emporium/$productId/': typeof EmporiumProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/About': typeof AboutIndexRoute
  '/Emporium': typeof EmporiumIndexRoute
  '/Emporium/$productId': typeof EmporiumProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/About/': typeof AboutIndexRoute
  '/Emporium/': typeof EmporiumIndexRoute
  '/Emporium/$productId/': typeof EmporiumProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/About/' | '/Emporium/' | '/Emporium/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/About' | '/Emporium' | '/Emporium/$productId'
  id: '__root__' | '/' | '/About/' | '/Emporium/' | '/Emporium/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  EmporiumIndexRoute: typeof EmporiumIndexRoute
  EmporiumProductIdIndexRoute: typeof EmporiumProductIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Emporium/': {
      id: '/Emporium/'
      path: '/Emporium'
      fullPath: '/Emporium/'
      preLoaderRoute: typeof EmporiumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About/': {
      id: '/About/'
      path: '/About'
      fullPath: '/About/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Emporium/$productId/': {
      id: '/Emporium/$productId/'
      path: '/Emporium/$productId'
      fullPath: '/Emporium/$productId/'
      preLoaderRoute: typeof EmporiumProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  EmporiumIndexRoute: EmporiumIndexRoute,
  EmporiumProductIdIndexRoute: EmporiumProductIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
